package com.example.clock.data

import com.example.clock.di.DatabaseModule
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Guards the migration contract.
 *
 * The database is built without a destructive fallback, so shipping a schema
 * change without a migration is a crash on open rather than a silent wipe of
 * every alarm. These tests turn that crash into a build failure: they check the
 * committed schemas and the migration chain keep up with `AppDatabase.version`.
 *
 * To change the schema: bump the version, commit the regenerated
 * `app/schemas/…/<version>.json`, and add a step to [DatabaseModule.MIGRATIONS].
 * Executing the migrations against real database files belongs in an
 * instrumentation test (MigrationTestHelper reads the schemas from assets, which
 * Robolectric does not surface).
 */
class MigrationTest {

    private val currentVersion = AppDatabase.VERSION

    private val schemaDir = File("schemas/${AppDatabase::class.java.canonicalName}")

    @Test
    fun schemaForEveryVersionIsCommitted() {
        val missing = (1..currentVersion).filterNot { File(schemaDir, "$it.json").exists() }

        assertTrue(
            "Missing exported schema(s) $missing in ${schemaDir.path}. They are generated by " +
                "the build — commit them, or a migration can never be written against them.",
            missing.isEmpty()
        )
    }

    /** Room needs a single-step path from every old version to the current one;
     *  a gap means those users crash on open. */
    @Test
    fun migrationChainCoversEveryVersion() {
        val steps = DatabaseModule.MIGRATIONS
            .map { it.startVersion to it.endVersion }
            .sortedBy { it.first }

        var expected = 1
        for ((start, end) in steps) {
            assertEquals("Gap in the migration chain before version $expected", expected, start)
            assertEquals("Migrations must move one version at a time", start + 1, end)
            expected = end
        }
        assertEquals(
            "AppDatabase is at version $currentVersion but MIGRATIONS only reaches $expected — " +
                "users on older versions would crash on open.",
            currentVersion, expected
        )
    }
}
